# Generated by Django 5.2.9 on 2026-01-19 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0004_remove_auditlog_notes_remove_auditlog_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledevent',
            name='related_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calendar_app.scheduledevent'),
        ),
    ]
